// Generated by https://quicktype.io

export interface Comanda {
    success: boolean;
    cliente: ClienteElement[];
}

export interface ClienteElement {
    _id:      string;
    cliente:  ClienteCliente;
    mesa:     Mesa;
    tipo:     Estado;
    cuenta:   Cuenta;
    personal: Personal[];
    detalle:  Detalle[];
    __v?:     number;
    estado?:  Estado;
}

export interface ClienteCliente {
    nombre:    string;
    correo:    string;
    direccion: string;
    celular:   string;
}

export interface Cuenta {
    subtotal:      number;
    total:         number;
    medio_de_pago: Estado;
    comentario:    string;
    estado:        Estado;
}

export interface Estado {
    clave: string;
    glosa: string;
}

export interface Detalle {
    producto:   Producto;
    cantidad:   number;
    monto_neto: number;
    comentario: string;
    _id?:       string;
}

export interface Producto {
    nombre:       string;
    descripcion:  string;
    precio:       number;
    popularidad?: number;
    tipo:         Estado;
    _id?:         string;
    estado?:      Estado;
}

export interface Mesa {
    nombre:    string;
    capacidad: number;
    piso:      number;
    ubicacion: string;
}

export interface Personal {
    rut:           string;
    nombre:        string;
    direccion:     string;
    celular:       string;
    fecha_ingreso: string;
    _id?:          string;
}
