// Generated by https://quicktype.io

export interface ComandasResultado {
    success:  boolean;
    comandas: Comanda[];
}

export interface Comanda {
    _id:      string;
    cliente?:  Cliente;
    mesa?:     Mesa;
    tipo:     Tipo;
    cuenta:   Cuenta;
    personal?: Personal[];
    detalle:  Detalle[];
    __v?:     number;
    estado?:  Estado;
}

export interface Cliente {
    nombre:    string;
    correo:    string;
    direccion: string;
    celular:   string;
}

export interface Cuenta {
    subtotal:      number;
    propina?:      number;
    total:         number;
    medio_de_pago: MedioDePago;
    comentario:    string;
    estado:        Estado;
}

export interface Estado {
    clave: string;
    glosa: string;
}

export interface Tipo {
    clave: string;
    glosa: string;
}

export interface MedioDePago {
    clave: string;
    glosa: string;
}

export interface Detalle {
    producto:   Producto;
    cantidad:   number;
    monto_neto: number;
    comentario: string;
    _id?:       string;
}

export interface Producto {
    nombre:       string;
    descripcion:  string;
    precio:       number;
    popularidad?: number;
    tipo:         Tipo;
    _id?:         string;
    estado?:      Estado;
}

export interface Mesa {
    nombre:    string;
    capacidad: number;
    piso:      number;
    ubicacion: string;
}

export interface Personal {
    rut:           string;
    nombre:        string;
    direccion:     string;
    celular:       string;
    fecha_ingreso: string;
    _id?:          string;
}
